baseURL = "http://example.org/"
languageCode = "en-us"
title = "Barnton Quarry"
theme = "bunker"

enableRobotsTXT = true
enableGitInfo = true
sectionPagesMenu = "main"

[params]
    description = "Useful explanations, code snippets, and projects gathered from a wide range of areas in computer science."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    fontawesome_sets = ["brands", "light"]
    copyright = "copyright info"

[[params.contact]]
    icon_type = "fab"
    icon_name = "facebook"
    link = "https://www.facebook.com/BarntonQuarryRestorationProject"
    text = "FB"

[[params.contact]]
    icon_type = "fal"
    icon_name = "envelope"
    link = "mailto:events@barntonquarry.org.uk"
    text = "MAIL"

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true