baseURL = "http://example.org/"
languageCode = "en-us"
title = "Barnton Quarry"
theme = "bunker"

enableRobotsTXT = true
enableGitInfo = true
sectionPagesMenu = "main"

[params]
    description = "Useful explanations, code snippets, and projects gathered from a wide range of areas in computer science."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    fontawesome_sets = ["brands"]
    copyright = "no monkeys (or typewriters) were harmed in the making of this site"